language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - flask db upgrade
  - python seed.py
# command to run tests
script:
  - python -m unittest discover
